branches:
  only:
  - master
language: python
python:
- 2.7
script:
- make github
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: LW6rYHziYRTD1x08sDdq7fJ9678EhNlvI0gSV/cixQ8rxy1pcqbRT93cSMFvhxHxeJFZIWUubgTxzyeQV6sxiLY4+FYrTCfW6mxljjJlUPaR2abCMGDgVSo3AmR72pgXvfrIR998SOAYGcU0WWf/DdUBx9YOsikOHc/i+u8WeYQ=
